# Generated by Django 5.2.4 on 2025-07-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "preview",
                    models.ImageField(
                        upload_to="course_previews/", verbose_name="Превью"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "preview",
                    models.ImageField(
                        upload_to="lesson_previews/", verbose_name="Превью"
                    ),
                ),
                ("video_url", models.URLField(verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
        ),
    ]
