# Generated by Django 5.2.4 on 2025-07-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="course_previews/", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="lesson_previews/", verbose_name="Превью"
            ),
        ),
    ]
