# Generated by Django 5.2.4 on 2025-07-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_preview_alter_lesson_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(null=True, verbose_name="Ссылка на видео"),
        ),
    ]
