# Generated by Django 5.2.4 on 2025-07-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
