# Generated by Django 5.2.4 on 2025-07-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
